### ISSUE TITLE
3.x-rc does not install into 4.5.2 targeted project 

### ISSUE THREAD

**Issue by clmcgrath** [bungeemonkee/Configgy#31]
When trying to install the latest  3.x RC version of Configgy into a console app targeting .net 4.5.2 the following error occurs 
``` 
Could not install package 'Configgy 3.0.2-rc3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			

```
	
when trying to do the same with 2.x the install works fine

**Comment by davelovesoftware** [comment]
Right. So the 3.X major version was re-targeted to support .NET Standard 1.5 which was a compromise to get support for .NET Core 1.0 but it meant losing some features (or moving them to other packages) and forcing the .NET Framework support version up to 4.6.1. This chart might help explain the compatibility of the various framework versions: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

I'm going to close this as it is the expected behavior given the stated design compromise.

Whenever I have a bit of time there are a few very minor tweaks I wanna make before promoting 3.X out of RC then I plan to begin work on 4.X which will force the required project versions up to .NET Standard 2.0, .NET Core 2.0, and .NET Framework 4.6.2 while unifying the .NET Framework stuff that was in 2.X (and moved to other packages for 3.X) and the .NET Core stuff back into the main Configgy plus hopefully include at least enhancements #27 and #28.

Side note: I did not realize anybody besides myself was using this package.  So that's awesome! I'll gladly take any feature suggestions for consideration in the 4.X versions. :)

**Comment by clmcgrath** [comment]
was going to try it out on a project i like the config overrides validation features, may add a few features myself 
i will up the target on my project to 4.6.2,  should be fine with what i have coded so far

**Comment by davelovesoftware** [comment]
Hi @clmcgrath I got some time to produce an alpha version working on .Net Standard 2.0 so per this chart (https://docs.microsoft.com/en-us/dotnet/standard/net-standard) it should work with any .Net 4.6.1 project so long as you also have the .Net Core 2.0 SDK.

Keep in mind there are a few more features I wanna add which may change some internal apis a bit. But you're free to try out 4.0.0-alpha01 and let me know what you think.
